# ?? APPLICATION ???????????????????????????????????????????????????????????????
spring.application.name=decision-service
server.port=8080

# ?? DATABASE ??????????????????????????????????????????????????????????????????
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool ? HikariCP (Spring Boot default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# ?? JPA ???????????????????????????????????????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# validate ? checks your entities match the schema on startup
# does NOT create or modify tables ? you did that manually in DBeaver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ?? JWT ???????????????????????????????????????????????????????????????????????
jwt.secret=${JWT_SECRET}
# 1 hour in milliseconds ? 1000 * 60 * 60
jwt.expiration=3600000

# ?? TEST AUTH (remove in production) ?????????????????????????????????????????
test.client.id=${TEST_CLIENT_ID}
test.client.secret=${TEST_CLIENT_SECRET}

# ?? RISK SCORING SERVICE ??????????????????????????????????????????????????????
risk.service.url=${RISK_SERVICE_URL}
risk.service.timeout.connect=500
risk.service.timeout.read=1000

# ?? CACHE ?????????????????????????????????????????????????????????????????????
spring.cache.type=caffeine
spring.cache.cache-names=policyConfig
spring.cache.caffeine.spec=maximumSize=1,expireAfterWrite=3600s

# ?? ASYNC ?????????????????????????????????????????????????????????????????????
# thread pool for @Async audit writes
async.core-pool-size=2
async.max-pool-size=10
async.queue-capacity=500
async.thread-name-prefix=audit-async-

# ?? LOGGING ???????????????????????????????????????????????????????????????????
logging.level.root=INFO
logging.level.com.fintech.decision=INFO


spring.security.user.password=disabled

